# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: httpimagestore 1.9.0 ruby lib

Gem::Specification.new do |s|
  s.name = "httpimagestore"
  s.version = "1.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jakub Pastuszek"]
  s.date = "2015-05-25"
  s.description = "Thumbnails images using httpthumbnailer and stored data on HTTP server (S3)"
  s.email = "jpastuszek@gmail.com"
  s.executables = ["httpimagestore"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/httpimagestore",
    "lib/httpimagestore/aws_sdk_regions_hack.rb",
    "lib/httpimagestore/configuration.rb",
    "lib/httpimagestore/configuration/file.rb",
    "lib/httpimagestore/configuration/handler.rb",
    "lib/httpimagestore/configuration/handler/source_store_base.rb",
    "lib/httpimagestore/configuration/handler/statement.rb",
    "lib/httpimagestore/configuration/identify.rb",
    "lib/httpimagestore/configuration/output.rb",
    "lib/httpimagestore/configuration/path.rb",
    "lib/httpimagestore/configuration/request_state.rb",
    "lib/httpimagestore/configuration/s3.rb",
    "lib/httpimagestore/configuration/source_failover.rb",
    "lib/httpimagestore/configuration/thumbnailer.rb",
    "lib/httpimagestore/error_reporter.rb",
    "lib/httpimagestore/ruby_string_template.rb"
  ]
  s.homepage = "http://github.com/jpastuszek/httpimagestore"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.7"
  s.summary = "HTTP based image storage and thumbnailer"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<unicorn-cuba-base>, ["~> 1.5.0"])
      s.add_runtime_dependency(%q<httpthumbnailer-client>, ["~> 1.3.0"])
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 1.10"])
      s.add_runtime_dependency(%q<mime-types>, ["~> 1.17"])
      s.add_runtime_dependency(%q<sdl4r>, ["~> 0.9"])
      s.add_runtime_dependency(%q<msgpack>, ["~> 0.5"])
      s.add_runtime_dependency(%q<addressable>, ["~> 2.3"])
      s.add_development_dependency(%q<faraday>, [">= 0.8"])
      s.add_development_dependency(%q<rspec>, ["~> 2.13"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.8", "~> 1.8"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.9"])
      s.add_development_dependency(%q<daemon>, ["~> 1"])
      s.add_development_dependency(%q<prawn>, ["= 0.8.4"])
      s.add_development_dependency(%q<httpthumbnailer>, [">= 0"])
    else
      s.add_dependency(%q<unicorn-cuba-base>, ["~> 1.5.0"])
      s.add_dependency(%q<httpthumbnailer-client>, ["~> 1.3.0"])
      s.add_dependency(%q<aws-sdk>, ["~> 1.10"])
      s.add_dependency(%q<mime-types>, ["~> 1.17"])
      s.add_dependency(%q<sdl4r>, ["~> 0.9"])
      s.add_dependency(%q<msgpack>, ["~> 0.5"])
      s.add_dependency(%q<addressable>, ["~> 2.3"])
      s.add_dependency(%q<faraday>, [">= 0.8"])
      s.add_dependency(%q<rspec>, ["~> 2.13"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.8", "~> 1.8"])
      s.add_dependency(%q<rdoc>, ["~> 3.9"])
      s.add_dependency(%q<daemon>, ["~> 1"])
      s.add_dependency(%q<prawn>, ["= 0.8.4"])
      s.add_dependency(%q<httpthumbnailer>, [">= 0"])
    end
  else
    s.add_dependency(%q<unicorn-cuba-base>, ["~> 1.5.0"])
    s.add_dependency(%q<httpthumbnailer-client>, ["~> 1.3.0"])
    s.add_dependency(%q<aws-sdk>, ["~> 1.10"])
    s.add_dependency(%q<mime-types>, ["~> 1.17"])
    s.add_dependency(%q<sdl4r>, ["~> 0.9"])
    s.add_dependency(%q<msgpack>, ["~> 0.5"])
    s.add_dependency(%q<addressable>, ["~> 2.3"])
    s.add_dependency(%q<faraday>, [">= 0.8"])
    s.add_dependency(%q<rspec>, ["~> 2.13"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.8", "~> 1.8"])
    s.add_dependency(%q<rdoc>, ["~> 3.9"])
    s.add_dependency(%q<daemon>, ["~> 1"])
    s.add_dependency(%q<prawn>, ["= 0.8.4"])
    s.add_dependency(%q<httpthumbnailer>, [">= 0"])
  end
end

